const TermsAndConditions = () => {
  return (
    <div className="max-w-5xl mx-auto px-4 py-10 text-gray-90 first-letter:capitalize">
      <h1 className="text-4xl font-bold mb-8 text-center">Terms of Service</h1>
      <p className="mb-6 text-md text-gray-600 text-center">
        Please read these terms and conditions carefully before using our
        services
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">1. General</h2>
      <p className="mb-2">
        In terms of the Information Technology Act, 2008, this document is an
        electronic record. Being generated by a computer system it does not
        require any physical or digital signatures.
      </p>
      <p className="mb-2">
        This document is publishedin accordance with the provisions of Rule 3
        (1) of the Information Technology (Intermediaries guidelines) Rules.
      </p>
      <p className="mb-2">
        The domain name sportshunt.in (hereinafter referred to as
        "Website/Portal /Platform") is owned by ATHLOSSPORTSHUNT LLP, a Company
        registered under the Companies Act, 2013, as amended, and having its
        registered office at B2 -013 Sobha Opal 39th cross 18th main Jayanagar
        4T block Bangalore - 560041 India (hereinafter referred to as ‘the
        company’).
      </p>
      <p className="mb-2">
        {" "}
        This Agreement consists of the following terms and conditions
        (hereinafter the "General Terms") and terms and conditions, if any,
        specific to use of individual Services (hereinafter the "Service
        Specific Terms"). The General Terms and Service Specific Terms are
        collectively referred to as the "Terms". In the event of a conflict
        between the General Terms and Service Specific Terms, the Service
        Specific Terms shall prevail.
      </p>
      <p className="mb-2">
        {" "}
        The use of this website by You is solely governed by this policy and any
        other policy so mentioned by terms of reference. By accessing the home
        page of the Website, gaining access to the Tournaments or using any of
        the services available on the Website shall be taken to mean that You
        have read and agreed to all of the policies so binding on You and that
        You are contracting with the Company and have undertaken binding
        obligations with the Company.
      </p>
      <p className="mb-2">
        {" "}
        For the purpose of these Terms of Use, wherever the context so requires
        "You" or "User" shall mean any natural or legal person who has gained
        access to the Website by using the sign-on systems linked to third
        parties or by providing Registration Data while registering on the
        Website. The Term shall include Players and other natural and legal
        persons who use / browse the Website or use the Website to enrol or
        participate in Tournaments.
      </p>
      <p className="mb-2">
        {" "}
        The term "We", "Us", "Our" shall mean ATHLOSSPORTSHUNT LLP. The term
        "Tournament" shall mean any competitive sport or physical activity
        through organised participation, through the Website and otherwise. The
        term "Organizer" shall mean the natural or legal person organising any
        Tournament. The term "Player" shall mean the natural persons enrolling
        or participating in Tournaments through the Website.
      </p>
      <p className="mb-2">
        {" "}
        You will be subject to the rules, guidelines, policies, terms, and
        conditions applicable to any service that is provided by this Website,
        and they shall be deemed to be incorporated into this Terms of Use and
        shall be considered as part and parcel of these Terms. We hold the sole
        right to modify the Terms of Use without prior permission from You or
        prior intimation to You. The relationship creates on You a duty to
        periodically check the terms and stay updated on its requirements. If
        You continue to use the website following such a change, this is deemed
        as consent by You to the so amended policies. As long as You comply with
        these Terms of Use, We grant You a personal, non-exclusive,
        non-transferable, limited privilege to access and use the Website and
        the services contained therein including Tournament enrolments.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">2. General/About Us</h2>
      <p className="mb-2">
        {" "}
        Sportshunt is a premier sports platform designed to benefit both players
        and tournament organizers. Players can easily join local tournaments and
        track their match history, while organizers have access to a
        comprehensive tournament management system that eliminates the need for
        traditional pen and paper based processes.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        3. Intermediary Platform
      </h2>
      <p className="mb-2">
        1. The Website is a platform that Players utilise to discover and enrol
        for Tournaments, interact ,and collaborate with other users including
        Organisers. We are not a party to any interaction between Users and take
        no liability that arises from any such communication or interaction. We
        act as a platform for Users to bring forth Tournaments and Tournament
        enrolments into the public domain.
      </p>
      <p className="mb-2">
        2. All communications between Users which inter alia includes new
        Tournaments and enrolments for all Tournaments are outcomes of the
        communication between the Users. We do not have any control over the
        content made available by an Organiser, play no determinative role in
        the Tournament, and have no determinative say on the terms of enrolment
        by Players in Tournaments. We are not liable for the outcomes of any
        such communication or collaboration.
      </p>
      <p className="mb-2">
        3. We do not endorse any of the Players, Organizers, Tournaments, or
        Tournament related content on the website, nor provide any guarantees as
        to its nature, content, quality, or originality.
      </p>
      <p className="mb-2">
        4.Subject to the above, a contract may exist between the Users and as
        such any breach of such contract and any claim arising from such breach
        is the subject matter of the terms of collaboration between them and we
        are in no way a party to such breach or involved in any suit arising
        from the same breach. The contact or communication arising from such
        breach shall be between the Users directly without Our involvement.
      </p>
      <p className="mb-2">
        5. While enrolling for any Tournament on the Website or entering into
        any collaboration with any Organiser or Player, or enrolling any Player
        for any Tournament, you are expected to check the creditworthiness of
        the Organizer and the genuineness of all information offered by them. We
        are not liable for the same.
      </p>
      <p className="mb-2">
        6. As the Tournament and Tournament enrolment is limited to the Users we
        are in no way liable for any deficiency of service that may arise which
        includes and is not limited to services not meeting expectations of the
        User, incorrect information, or such content/information that is in
        breach of intellectual property rights of third parties. It is solely a
        Player’s responsibility to verify the content, and truthfulness about
        any Tournament or Organizer. It is solely the Organizer’s responsibility
        to verify the truthfulness of any content provided by the Player.
      </p>
      <p className="mb-2">
        Disclaimer: DUE TO SOME TECHNICAL ISSUES, TYPOGRAPHICAL OR HUMAN ERRORS,
        IMAGES, RATINGS, PORTFOLIOS, TOURNAMENT INFORMATION, CONTENT, TEXT
        DOCUMENTS AND ANY INFORMATION RELATED TO USERS OR TOURNAMENTS MAY BE
        INCORRECTLY REFLECTED ON THE WEBSITE.
      </p>
      <p className="mb-2">
        7. You release and indemnify Us and / or any of Our directors, officers,
        employees and representatives from any cost, damage, liability or other
        consequence of any of the actions of the Users of the Website and
        specifically waive any claims that you may have in this behalf under any
        applicable law.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        4. Membership and Terms Of Acceptance{" "}
      </h2>
      <p className="mb-2">
        You must be of legal age to enter into a binding agreement in order to
        accept the Terms. If you do not agree to the General Terms, do not use
        any of our Services. If you agree to the General Terms and do not agree
        to any Service Specific Terms, do not use the corresponding Service. You
        can accept the Terms by checking a checkbox or clicking on a button
        indicating your acceptance of the terms or by actually using the
        Services, or by accessing and using the Website.
      </p>
      <p className="mb-2">
        Without limitation to the foregoing, in the event you are barred from
        undertaking legally binding obligations under the Indian Contract Act,
        1872, or are for any reason, unable to provide ‘Consent’ as per the
        Information Technology (Reasonable security practices and procedures and
        sensitive personal data or information) Rules, 2011, you are not
        eligible to register for, use or avail the services available on the
        Website.
      </p>
      <p className="mb-2">
        By using the Website and/or the Services, you represent and warrant that
        you have the right, authority, and capacity to enter into these Terms of
        Use and to abide by all of the terms and conditions set forth herein.
        The Website is administered in India and is intended for Indian users;
        any use outside of India is at the user’s own risk and users are
        responsible for compliance with any local laws applicable to their use
        of the Services or the Website.
      </p>
      <p className="mb-2">
        Without limiting any other provisions of these Terms, you may not use
        this Website for any purpose that is unlawful or prohibited by these
        Terms and/or any applicable additional terms. Your access to this
        Website may be terminated immediately, in our sole discretion, with or
        without notice, if you fail to comply with any provision of these Terms
        and/or additional terms, or for any other reason, or no reason.
      </p>
      <p className="mb-2">
        Access to certain areas of the Website is available only to registered
        Members. To become a registered Member, you are required to answer a
        limited number of mandatory questions. You represent and warrant that
        all information which you supply to us about yourself and others, is
        true and accurate.
      </p>
      <p className="mb-2">
        We do not recommend or endorse any specific Tournaments, Organizers,
        opinions, or other information that may appear on the Website. If you
        rely on any of the Information provided on the Website, you do so solely
        at your own risk.
      </p>
      <p className="mb-2">
        As part of the registration process, you will provide an email address,
        mobile number and create a password. These are your credentials for
        accessing your account, and the Services that are only available to
        members ("Credentials'').
      </p>
      <p className="mb-2">
        If you provide any information that is untrue, inaccurate, out of date
        or incomplete (or becomes untrue, inaccurate, out of date or
        incomplete), or We have reasonable grounds to suspect that the
        information provided by you is untrue, inaccurate, out of date or
        incomplete, We may, in our sole discretion, discontinue the provision of
        the Services to you.
      </p>
      <p className="mb-2">
        The specific terms relating to such accounts are as below, without
        prejudice to the rest of these Terms and the Privacy Policy. Your
        Account is only created after you have signed up and explicitly accepted
        these Terms. In the event you wish to delete your Account, you may do so
        by accessing ‘Profile’ from within your account. This will ensure that
        your account and any associated records will be deleted from the
        Account. This will however not delete your records stored by Organizers.
      </p>
      <p className="mb-2">
        You should keep your Credentials private and not share your Credentials
        with anyone else. You are responsible for notifying us if your password
        has been hacked or stolen. You may notify us by sending an email to
        Cto@sportshunt.in
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        5. Intellectual Property
      </h2>
      <p className="mb-2">
        This website is the sole and exclusive property of ATHLOSSPORTSHUNT LLP
        or its licensors and vendors. Except for posted content that you or any
        other visitors to the Website submit (‘Posted Content’).You acknowledge
        that the Services and any underlying technology or software used in
        connection with the Services contain ATHLOSSPORTSHUNT proprietary
        information. We give you permission to use the aforementioned content
        for personal, non-commercial purposes only and do not transfer any
        intellectual property rights to you by virtue of permitting your use of
        the Services. You may print, download, and store information from the
        Website for your own convenience, but you may not copy, distribute,
        republish (except as permitted in this paragraph), sell, or exploit any
        of the content, or exploit the Website in whole or in part, for any
        commercial gain or purpose whatsoever. Except as is expressly and
        unambiguously provided herein, ATHLOSSPORTSHUNT and its suppliers do not
        grant you any express or implied rights, and all rights in the Website
        and the Services not expressly granted by ATHLOSSPORTSHUNT to you are
        retained by ATHLOSSPORTSHUNT.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        6. Information Presentation
      </h2>
      <p className="mb-2">
        We make the Website available as a service to users, Players and
        Organizers for the purposes of providing an informative and educational
        resource. We may, but have no obligation to, have non user-posted
        information reviewed by the Website's editorial personnel.
        <br></br>It is important to note, however, that the timeliness and
        accuracy of any or all of the Information is not guaranteed. Neither the
        authors, the editorial personnel, nor any other party who has been
        involved in the preparation or publication of this work can assure you
        that the Information contained herein is in every respect accurate or
        complete, and they are not responsible for any errors or omissions or
        for the results obtained from the use of such information.{" "}
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        7. Third Party Information
      </h2>
      <p className="mb-2">
        All text, graphics, user interfaces, visual interfaces, photographs,
        trademarks, logos, sounds, music and artwork collected from publicly
        available information (collectively, "Third Party Content"), is a
        third-party generated content and We have no control over such
        third-party generated content as We are merely an intermediary for the
        purposes of this Terms of Use.
        <br></br>Other than when provided for, the use of such content and it
        being reproduced, republished, uploaded, posted, publicly displayed,
        encoded, translated, transmitted or distributed in any way (including
        mirroring) to any other computer, server, Website or other medium for
        publication or distribution or for any commercial enterprise, without
        Our express prior written consent is not allowed.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">8. Posted Content</h2>
      <p className="mb-2">
        As a User (including an Organiser and a Player), you will have the
        opportunity to submit content and information pertaining to Tournaments,
        to submit inquiries concerning Players, Organizers, other Users and
        Tournaments and to participate in the other interactive and community
        features of the Website. It is important that you act responsibly when
        providing Posted Content.
        <br></br>All Posted Content shall be submitted in accordance with
        applicable law. Further, the option of Users to submit Posted Content
        shall be at ATHLOSSPORTSHUNT sole discretion and may be modified or
        withdrawn at its sole discretion.ATHLOSSPORTSHUNT may moderate such
        Posted Content at any time. However, ATHLOSSPORTSHUNT shall not be
        obliged to act in any manner to give effect to the content of Posted
        Content, such as suggestions for delisting of a particular Organiser,
        User, or Player from the Website. We reserve the right to publish your
        Posted Content as part of the Service and to also to remove your posted
        information for any reason. We are not, however, responsible for any
        failure or delay in removing Posted Content. Keep in mind that the
        Posted Content of others is simply opinion and should not be relied on.
      </p>
      <ol className="list-decimal pl-6 mb-4">
        <li className="mb-2">
          You are solely responsible for any Posted Content that you submit,
          publish or display on the Website or transmit to other members and/or
          other users of the Website.
        </li>
        <li className="mb-2">
          You may not post, distribute, or reproduce in any way any copyrighted
          material, trademarks, or other proprietary information without
          obtaining the prior written consent of the owner of such proprietary
          rights. You may not submit any content or material that infringes,
          misappropriates or violates the intellectual property, publicity,
          privacy or other rights of any party.
        </li>
        <li className="mb-2">
          You may not provide any Posted Content that falsely expresses or
          implies that such content or material is sponsored or endorsed by
          ATHLOSSPORTSHUNT.
        </li>
        <li className="mb-2">
          You may not provide any Posted Content that is unlawful or that
          promotes or encourages illegal activity.
        </li>
        <li className="mb-2">
          You understand and agree that ATHLOSSPORTSHUNT may (but is not
          obligated to) review and delete any Posted Content that in the sole
          judgement of ATHLOSSPORTSHUNT violates these Terms of Use or which
          might be offensive, illegal, or that might violate the rights of,
          harm, or threaten the safety of other users or members of the Website
          and/or other website users.
        </li>
        <li className="mb-2">
          You agree that you will only provide Posted Content that you believe
          to be true and you will not purposely provide false or misleading
          information.
        </li>
      </ol>

      <p className="mb-2">
        9. By posting Posted Content on the Website, you agree to and hereby do
        grant, and you represent and warrant that you have the right to
        grant,ATHLOSSPORTSHUNT, its contractors, and the users of the Website an
        irrevocable, perpetual, royalty-free, fully sub-licensable, fully paid
        up, worldwide licence to use, copy, publicly perform, digitally perform,
        publicly display, and distribute such Posted Content and to adapt, edit,
        translate, prepare derivative works of, or incorporate into other works,
        such Posted Content. This licence is non-exclusive, except you agree
        that ATHLOSSPORTSHUNT shall have the exclusive right to practise this
        licence to the extent of combining your Posted Content with the Posted
        Content of other ATHLOSSPORTSHUNT users for purposes of constructing or
        populating a searchable database of reviews and information. The
        following is a partial list of the kind of content and communications
        that are illegal or prohibited on/through the Website. ATHLOSSPORTSHUNT
        reserves the right to investigate and take appropriate legal action in
        its sole discretion against anyone who violates this provision,
        including without limitation, removing the offending communication from
        the Services and terminating the membership of such violators or
        blocking your use of the Services and/or the Website. You may not post
        content that:
      </p>
      <ol className="list-decimal pl-6 mb-4">
        <li className="mb-2">
          Involves the transmission of unsolicited mass mailing or "spamming".
        </li>
        <li className="mb-2">
          Harasses or advocates harassment of another person.
        </li>
        <li className="mb-2">Is false or intentionally misleading.</li>
        <li className="mb-2">
          Violates the intellectual property or other rights of any person.
        </li>
        <li className="mb-2">
          Is threatening, obscene, defamatory or libellous.
        </li>
        <li className="mb-2">
          Is pornographic or sexually explicit in nature.
        </li>
      </ol>

      <h2 className="text-2xl font-semibold mt-8 mb-4">10. User Obligations</h2>
      <p className="mb-2">
        You are a restricted user of this website. You are responsible for all
        use of the Website and for all use of your Credentials, including use by
        others to whom you have given your Credentials. You may use the Website
        and the Services for lawful purposes only. You may not use the Website
        in any manner that could damage, disable, overburden, or impair our
        servers or networks, or interfere with any other party's use and
        enjoyment of the Website or the Services. You may not attempt to gain
        unauthorised access to any of the Services, user accounts, or computer
        systems or networks, through hacking, cracking, intrusion to network,
        password mining or any other means. Without limiting any of the
        foregoing, you agree that you shall not (and you agree not to allow any
        third party to):
      </p>
      <ol className="list-decimal pl-6 mb-4">
        <li className="mb-2">
          Copy, modify, adapt, translate, or reverse engineer any portion of the
          Website, its content or materials and/or the Services.
        </li>
        <li className="mb-2">
          Remove any copyright, trademark or other proprietary rights notices
          contained in or on the Website and/or the Services or in or on any
          content or other material obtained via the Website and/or the
          Services.
        </li>
        <li className="mb-2">
          Use any robot, spider, site search/retrieval application, or other
          automated device, process or means to access, retrieve or index any
          portion of the Website and/or the Services.
        </li>
        <li className="mb-2">
          Access, retrieve or index any portion of the Website and/or the
          Services for purposes of constructing or populating a searchable
          database.
        </li>
        <li className="mb-2">
          Reformat or frame any portion of the web pages that are part of the
          Website and/or the Services.
        </li>
        <li className="mb-2">
          Threaten the unity, integrity, defence, security or sovereignty of
          India, friendly relations with foreign states, or public order, or
          cause incitement to the commission of any cognizable offence or
          investigation of any offence or is insulting any other nation.
        </li>
        <li className="mb-2">
          Violate any code of conduct or other guidelines, which may be
          applicable for or to any particular Service;
        </li>
        <li className="mb-2">
          Use the Website or any material or content for any purpose that is
          unlawful or prohibited by these Terms of Use, or the laws of India, or
          to solicit the performance of any illegal activity or other activity
          which infringes the rights of this website or other third parties.
        </li>
        <li className="mb-2">
          Publish, post, disseminate information that is false, inaccurate or
          misleading; violate any applicable laws or regulations for the time
          being in force in or outside India.
        </li>
        <li className="mb-2">
          Disrupt or interfere with the security of, or otherwise cause harm to
          the Website, systems resources, accounts, passwords, servers or
          networks connected to or accessible through the Websites or any
          affiliated or linked sites.
        </li>
        <li className="mb-2">
          Publish, post, or disseminate, any information which is grossly
          harmful, harassing, blasphemous, defamatory, obscene, pornographic,
          paedophilic, libellous, invasive of another's privacy, hateful, or
          racially, ethnically objectionable, disparaging, or otherwise unlawful
          in any manner whatever; or unlawfully threatening or unlawfully
          harassing including but not limited to indecently representing women
          within the meaning of the Indecent Representation of Women
          (Prohibition) Act, 1986.
        </li>
        <li className="mb-2">
          Create user accounts by automated means or under false or fraudulent
          pretences.{" "}
        </li>
        <li className="mb-2">
          Collect or store personal data about other users in connection with
          the prohibited activities described in this paragraph.
        </li>
      </ol>
      <p className="mb-2">
        11. You may not reverse look-up, trace or seek to trace any information
        on any other user, of or visitor to, the Website, or any other customer
        or vendor of the website, including any website Account not owned by
        You, to its source, or exploit the Website or Service or information
        made available or offered by or through the Website, in any way whether
        or not the purpose is to reveal any information, including but not
        limited to personal identification information, other than Your own
        information, as provided for by the Website.
        <br></br>In addition to our rights in these Terms of Use, we may take
        any legal action and implement any technical remedies to prevent the
        violation of this provision and to enforce these Terms of Use.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        12. Disclaimer of Warranties and Liabilities
      </h2>
      <p className="mb-2">
        You expressly understand and agree that, to the maximum extent permitted
        by applicable law:
        <br></br>The website, services and other materials are provided by this
        website is on an "as is" basis without warranty of any kind, express,
        implied, statutory or otherwise, including the implied warranties of
        title, non-infringement, merchantability or fitness for a particular
        purpose. Without limiting the foregoing, the website makes no warranty
        that
      </p>

      <ol className="list-decimal pl-6 mb-4">
        <li className="mb-2">
          Your requirements will be met or that access to the contents on the
          website will be uninterrupted, timely, secure or error-free.
        </li>
        <li className="mb-2">
          Materials, information obtained, and results will be effective,
          accurate or reliable.
        </li>
        <li className="mb-2">
          Portfolios, tournament descriptions, organiser descriptions, and
          player descriptions shall be true, accurate or reliable.
        </li>
        <li className="mb-2">
          Any errors or defects in the website, services or other materials will
          be corrected.
        </li>
      </ol>

      <p className="mb-2">
        13. To the maximum extent permitted by applicable law, we will have no
        liability related to user content arising under intellectual property
        rights, libel, privacy, publicity, obscenity or other laws. The website
        also disclaims all liability with respect to the misuse, loss,
        Modification or unavailability of any user content.
        <br></br>The user understands and agrees that any material or data
        downloaded or otherwise obtained through the website is done entirely at
        their own discretion and risk and they will be solely responsible for
        any damage to their computer systems or loss of data that results from
        the download of such material or data. The website accepts no liability
        for any errors or omissions, with respect to any information provided to
        you whether on behalf of itself or third parties.
        <br></br>We shall not be liable for any third-party product or services.
        Any advertisements shown on the website with respect to the third-party
        websites or the products and services are for informational purpose
        only.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        14. Indemnification and Limitation of Liability
      </h2>
      <p className="mb-2">
        You agree to indemnify, defend and hold harmless this website including
        but not limited to its officers, directors, and employees from and
        against any and all losses, liabilities, claims, damages, demands, costs
        and expenses (including legal fees and disbursements in connection
        therewith and interest chargeable thereon) asserted against or incurred
        by us that arise out of, result from, or may be payable by virtue of,
        any breach or non-performance of any representation, warranty, covenant
        or agreement made or obligation to be performed by you pursuant to these
        terms of use. Further, you agree to hold us harmless against any claims
        made by any third party due to, or arising out of, or in connection
        with, your use of the website, any claim that your material caused
        damage to a third party, your violation of the terms of use, or your
        violation of any rights of another, including any intellectual property
        rights.<br></br>The website, services and other materials are provided
        by this website is on an "as is" basis without warranty of any kind,
        express, implied, statutory or otherwise, including the implied
        warranties of title, non-infringement, merchantability or fitness for a
        particular purpose. Without limiting the foregoing, the website makes no
        warranty that in no event shall we, our officers, directors, or
        employees be liable to you or any third party for any special,
        incidental, indirect, consequential or punitive damages whatsoever,
        including those resulting from loss of use, data or profits, whether or
        not foreseeable or whether or not we have been advised of the
        possibility of such damages, or based on any theory of liability,
        including breach of contract or warranty, negligence or other tortious
        action, or any other claim arising out of or in connection with your use
        of or access to the website, services or materials.
        <br></br>The limitations and exclusions in this section apply to the
        maximum extent permitted by applicable law.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        15. Fees and Payments(Pro Subscription) 
      </h2>
      <p className="mb-2">
        Subscriptions to Services are available as per the prevailing
        subscription plans. Your subscription will be automatically renewed at
        the end of each subscription period unless you inform us that you do not
        wish to renew the subscription. The subscription fee will be charged to
        the payment mechanism last used by you. If you would like the payment
        for the renewal to be made through a different payment mechanism or if
        you do not wish to renew the subscription, you agree to inform us at
        least seven days prior to the renewal date.
        <br></br>In the event of termination of the subscription, you will be
        refunded the subscription fee for the unused portion of the subscription
        period. ATHLOSSPORTSHUNT reserves the right to change the subscription
        fee and to charge for use of Services that are currently available free
        of charge. You will not be charged for using any Service unless you have
        opted for a paid plan. For information on the subscription options and
        charges for all paid Services, you can write to us Cto@sportshunt.in
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        16. Payment and Disbursement Policy
      </h2>
      <ol className="list-decimal pl-6 mb-4">
        <li className="mb-2">
          <h4 className="font-bold">Registration Fees:</h4>
          All player registration fees for tournaments will be collected by
          ATHLOSSPORTSHUNT on behalf of the tournament organizers.
        </li>
        <li className="mb-2">
          <h4 className="font-bold">Withholding of Funds:</h4>
          ATHLOSSPORTSHUNT will withhold the registration fees from the
          organizers until two (2) days after the successful completion of the
          tournament. This period allows for verification of tournament results
          and resolution of any disputes or issues that may arise.
        </li>
        <li className="mb-2">
          <h4 className="font-bold">Disbursement to Organizers:</h4>
          After the two-day withholding period, and provided there are no
          unresolved disputes or issues, the collected registration fees will be
          disbursed to the organizer’s designated account.
        </li>
        <li className="mb-2">
          <h4 className="font-bold">Dispute Resolution:</h4>
          If any disputes or issues arise regarding the tournament,
          ATHLOSSPORTSHUNT reserves the right to extend the withholding period
          until the matter is resolved to the satisfaction of all parties.
        </li>
        <li className="mb-2">
          <h4 className="font-bold">Organizers' Responsibility:</h4>
          Organizers are responsible for ensuring the tournament is conducted in
          compliance with the rules and terms outlined during registration.
          Failure to do so may result in delayed payments or forfeiture of the
          registration fees, depending on the nature of the breach
        </li>
      </ol>

      <h2 className="text-2xl font-semibold mt-8 mb-4">18. Termination</h2>
      <p className="mb-2">
        ATHLOSSPORTSHUNT, may, at its sole discretion, at any time and without
        advance notice or liability, terminate or restrict your access to all or
        any component of our Website, even if access continues to be allowed to
        others. Upon such termination or suspension, you must immediately
        discontinue use of the Website, and destroy any copy you have made of
        any portion of the Website, including any contents accessed through the
        Website. Accessing the Website after such termination, suspension or
        discontinuation shall constitute an act of trespassing. We shall not be
        accountable to you for such suspension or termination.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">19. Entire Agreement</h2>
      <p className="mb-2">
        These Terms of Use and any supplemental terms, policies, rules and
        guidelines posted on the Website, including the Privacy Policy,
        constitute the entire agreement between you and us and supersede all
        previous written or oral agreements. If any part of these Terms of Use
        is held invalid or unenforceable, that portion shall be construed in a
        manner consistent with applicable law to reflect, as nearly as possible,
        the original intentions of the parties, and the remaining portions shall
        remain in full force and effect. The failure of ATHLOSSPORTSHUNT to
        exercise or enforce any right or provision of these Terms of Use shall
        not constitute a waiver of such right or provision. The failure of
        either party to exercise in any respect any right provided for herein
        shall not be deemed a waiver of any further rights hereunder.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">20. Governing Law</h2>
      <p className="mb-2">
        These Terms shall be governed and construed in accordance with the
        Indian laws.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        21. Dispute Resolution
      </h2>
      <p className="mb-2">
        Any controversy, dispute or claim arising out of or related to these
        Terms of Use or your use of the Services shall be subject to exclusive
        jurisdiction of the courts at Bangalore, Karnataka.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">22. Assignment</h2>
      <p className="mb-2">
        We may assign this contract at any time to any parent, subsidiary, or
        any affiliated company, or as part of the sale to, merger with, or other
        transfer of our company to another entity. We will post a notice on the
        Website regarding any change of ownership so that you have the
        opportunity to discontinue your use of the Website or cancel your
        registration if you do not wish to continue to use the Website and the
        Services under the new ownership. You may not assign, transfer or
        sub-license these Terms of Use to anyone else and any attempt to do so
        in violation of this section shall be null and void.
      </p>
    </div>
  );
};

export default TermsAndConditions;
